### ISSUE TITLE
iOS Chrome / Safari にて、Flexbox の gap が効いていない

### ISSUE THREAD

**Issue by y4shiro** [y4shiro/website#19]
<img src="https://user-images.githubusercontent.com/14056951/132684455-e74e11b2-41d7-42e4-818d-0dd609b98234.jpg" width="480px">
  
macOS の開発者ツールで確認したときは気が付かなかったが、iOS 実機でフッターの gap が効いていない事を確認した。  
Can I Use で確認した所、Flexbox の gap プロパティは iOS 14.5 から対応済みだが、マルチカラムでは非対応の模様。  
  
https://caniuse.com/mdn-css_properties_gap_flex_context
https://caniuse.com/mdn-css_properties_gap_multicol_context
  
非常に不可解なのが、今回は `display: flex;` を適用した上で gap プロパティを指定しているにも関わらず機能していない点。  

とりあえず margin あたりに置換して修正したい。

**Comment by y4shiro** [comment]
選択肢は 2 つあって、愚直に margin で指定する方法と column-gap / row-gap を使用する方法。  

1. margin で指定
```css
{
  display: flex;
  flex-direction: column-reverse;

  li:last-of-type {
    margin-bottom: 1rem;
  }

  @media (min-width: ${breakpoints.sm}px) {
    flex-direction: row;
    justify-content: space-between;

    li:last-of-type {
      margin-bottom: 0;
    }
  }
}
```

2. column-gap / row-gap で指定
https://caniuse.com/mdn-css_properties_column-gap_multicol_context

```css
{
  display: flex;
  flex-direction: column-reverse;
  row-gap: 1rem;

  @media (min-width: ${breakpoints.sm}px) {
    flex-direction: row;
    justify-content: space-between;
    row-gap: 0;
  }
}
```

2 の方が元々使用していた gap と同じ記述で済んで楽なので、こちらで試してダメそうなら 1 の方法で記述する。
